export ALLOW_MISSING_DEPENDENCIES=true
export FOX_VIRTUAL_AB_DEVICE=1
export FOX_AB_DEVICE=1
export OF_AB_DEVICE_WITH_RECOVERY_PARTITION=1
export FOX_USE_TAR_BINARY=1
export OF_USE_MAGISKBOOT=0
export FOX_RESET_SETTINGS=disabled
export OF_FLASHLIGHT_ENABLE=1
export OF_FL_PATH1="/sys/class/backlight/panel0-backlight/brightness"
export OF_HIDE_NOTCH=1
export OF_CLOCK_POS=2
export OF_DONT_KEEP_LOG_HISTORY=1
export FOX_TARGET_DEVICES=sky
export TARGET_DEVICE_ALT=river
export FOX_DELETE_MAGISK_ADDON=1
export OF_NO_REFLASH_CURRENT_ORANGEFOX=1


